### ISSUE TITLE
可以用Docker安装吗？

### ISSUE THREAD

**Issue by mwnu** [hibobmaster/matrix_chatgpt_bot#1]

**Comment by hibobmaster** [comment]
我写个Dockerfile, 然后就能docker安装了

**Comment by hibobmaster** [comment]
已添加docker部署支持
克隆整个项目到本地，修改`config.json`，然后 docker compose up 起来即可

**Comment by mwnu** [comment]
> 已添加 docker部署支持 克隆整个项目到本地，修改，然后 docker compose up 起来即可`config.json`

这就试下，不过对 dockerfile 不太熟悉，要是能上架 Docker Hub 就方便多了。

**Comment by mwnu** [comment]
不成功，卡在build环节，可能是网络问题。

**Comment by hibobmaster** [comment]
已上架 Docker Hub
https://github.com/hibobmaster/matrix_chatgpt_bot/commit/4c9ec31102c957d68609dcc75d0c4e0749f0f40b

**Comment by mwnu** [comment]
> 已上架 Docker Hub [4c9ec31](https://github.com/hibobmaster/matrix_chatgpt_bot/commit/4c9ec31102c957d68609dcc75d0c4e0749f0f40b)

能安装，我用Element Web登录生成的device_id，刚开始对话时回了个你好，后面就一直不回应了，没有日志的话也不知道问题出在哪。
然后不知道是不是只能在配置里指定了的房间对话，在别的房间邀请并 !chat !gpt 也是不回应的。

**Comment by hibobmaster** [comment]
如果需要在别的房间响应会话，不要在`config.json`里添加room_id.
> 刚开始对话时回了个你好，后面就一直不回应了

请问是否使用了大量的`!gpt`指令，api的提供者做了rate-limit
https://github.com/ayaka14732/ChatGPTAPIFree/commit/8c6bcf2c825bcf0edc58b687826edc8287b18728
我晚点加个选项吧，如果提供了api_key就默认使用官方的接口。

日志功能晚点加。

**Comment by mwnu** [comment]
> 

没有大量使用，就问了几次

**Comment by hibobmaster** [comment]
请pull最新的镜像，测试问题是否有所缓解

**Comment by hibobmaster** [comment]
抱歉, 这么久才发现我搞错了push到dockerhub的命令，一直用的`docker pull hibobmaster/matrixchatgptbot:latest`，代码一直是旧的，应该用`docker push`的。。。目前已解决了这个问题，请再测试一下。

此外 `compose.yaml` 也进行了一定的修改，以前的部署是无法保留容器内的数据库的。

**Comment by mwnu** [comment]
> 抱歉, 这么久才发现我搞错了push到dockerhub的命令，一直用的`docker pull hibobmaster/matrixchatgptbot:latest`，代码一直是旧的，应该用`docker push`的。。。目前已解决了这个问题，请再测试一下。
> 
> 此外 `compose.yaml` 也进行了一定的修改，以前的部署是无法保留容器内的数据库的。

没用，确实怎么问它都不会有回复。

**Comment by hibobmaster** [comment]
> > 抱歉, 这么久才发现我搞错了push到dockerhub的命令，一直用的`docker pull hibobmaster/matrixchatgptbot:latest`，代码一直是旧的，应该用`docker push`的。。。目前已解决了这个问题，请再测试一下。
> > 此外 `compose.yaml` 也进行了一定的修改，以前的部署是无法保留容器内的数据库的。
> 
> 没用，确实怎么问它都不会有回复。

能提供你的compose.yaml文件，以及config.json吗? 关键信息请自己去除。

我同样是docker部署，测试都是ok的。

更新容器，请问是否有使用 docker compose down ，如果没有请先执行该命令销毁容器，再重新创建，不然新的image会无法正常工作。

你也可以加入我们的matrix聊天室讨论
https://matrix.to/#/#public:matrix.qqs.tw

**Comment by mwnu** [comment]
> > > 抱歉, 这么久才发现我搞错了push到dockerhub的命令，一直用的`docker pull hibobmaster/matrixchatgptbot:latest`，代码一直是旧的，应该用`docker push`的。。。目前已解决了这个问题，请再测试一下。
> > > 此外 `compose.yaml` 也进行了一定的修改，以前的部署是无法保留容器内的数据库的。
> > 
> > 
> > 没用，确实怎么问它都不会有回复。
> 
> 能提供你的compose.yaml文件，以及config.json吗? 关键信息请自己去除。
> 
> 我同样是docker部署，测试都是ok的。
> 
> 更新容器，请问是否有使用 docker compose down ，如果没有请先执行该命令销毁容器，再重新创建，不然新的image会无法正常工作。
> 
> 你也可以加入我们的matrix聊天室讨论 https://matrix.to/#/#public:matrix.qqs.tw

**Comment by mwnu** [comment]
> > > > 抱歉, 这么久才发现我搞错了push到dockerhub的命令，一直用的`docker pull hibobmaster/matrixchatgptbot:latest`，代码一直是旧的，应该用`docker push`的。。。目前已解决了这个问题，请再测试一下。
> > > > 此外 `compose.yaml` 也进行了一定的修改，以前的部署是无法保留容器内的数据库的。
> > > 
> > > 
> > > 没用，确实怎么问它都不会有回复。
> > 
> > 
> > 能提供你的compose.yaml文件，以及config.json吗? 关键信息请自己去除。
> > 我同样是docker部署，测试都是ok的。
> > 更新容器，请问是否有使用 docker compose down ，如果没有请先执行该命令销毁容器，再重新创建，不然新的image会无法正常工作。
> > 你也可以加入我们的matrix聊天室讨论 https://matrix.to/#/#public:matrix.qqs.tw

我没有用 docker compose 安装，而是 docker run，映射了下配置：***/config.json:/app/config.json，配置是：
```
{
  "homeserver": "https://xxxxx.com:8448",
  "user_id": "@xxx:xxxx.com",
  "password": "xxxxxxxxxxxxx",
  "device_id": "xxxxxxx",
  "api_key": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
```

**Comment by hibobmaster** [comment]
@mwnu  有时间请再尝试一下最新版。

启动容器前，记得创建一个空的`db`文件，用于持久化数据库保存。

**Comment by mwnu** [comment]
> @mwnu 有时间请再尝试一下最新版。
> 
> 启动容器前，记得创建一个空的`db`文件，用于持久化数据库保存。

这会儿可以了
