### ISSUE TITLE
get only 1 image from Bing Image Creator instead of 4

### ISSUE THREAD

**Issue by jaodei** [hibobmaster/matrix_chatgpt_bot#11]
Bing Image Creator creates 4 images per prompt on its official website. But using !pic prompt, we only get one. Could you change the code so that all 4 are displayed?

**Comment by hibobmaster** [comment]
element or other matrix clients do not support something like image galleries. It can make mess up chatting timeline if we send four images one by one.

If you really need this function, i can add an option for you to enable it.

**Comment by jaodei** [comment]
Yes, I would like to have this. While I don't quite understand your concern, are you able to send the image one by one instead? Otherwise, four at one time is also acceptable. Cheers.

**Comment by hibobmaster** [comment]
Pull the latest container image and add `output_four_images` to your config file.
https://github.com/hibobmaster/matrix_chatgpt_bot/wiki/Bing-Image-Creator
https://github.com/hibobmaster/matrix_chatgpt_bot/commit/6ff585d402d037f7b2e0fb3db7049f41925f0d80

https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/84d3dba3-c246-4dcb-a887-ed7152aaca9a

**Comment by jaodei** [comment]
great. It works. Thank you a lot.
