### ISSUE TITLE
Support session isolation for chat,bing,bard commands

### ISSUE THREAD

**Issue by hibobmaster** [hibobmaster/matrix_chatgpt_bot#17]

**Comment by hibobmaster** [comment]
`!chat` and `!bing` command can use [node-chatgpt-api](https://github.com/waylaidwanderer/node-chatgpt-api) to refactor since it support parentMessageId

`!lc` command use [Flowise](https://github.com/FlowiseAI/Flowise) api. To achieve context conversation and session isolation need further investigation.

**Comment by jaodei** [comment]
Cool. So this feature will be available in v1.2.0? When will it be released? Cheers.

**Comment by hibobmaster** [comment]
`!bard` session isolation with context conversation. 
![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/3696b647-73e2-4381-a73c-da638eb1e50f)

bard response is much quicker than bing and chatgpt web.

**Comment by hibobmaster** [comment]
`!bing` session isolation with context conversation.
<img width="1473" alt="Snipaste_2023-06-04_21-17-04" src="https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/52794547-1b98-4a7a-9daa-6907830a74bb">
<img width="1555" alt="Snipaste_2023-06-04_21-19-34" src="https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/4e529c63-56ed-4ac4-98af-0cc6148293b2">

**Comment by hibobmaster** [comment]
`!chat`  session isolation with context conversation.
<img width="1462" alt="Snipaste_2023-06-04_22-36-11" src="https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/15ac16ba-5d96-4a69-9de5-ef0a14c4df35">

**Comment by hibobmaster** [comment]
The current langchain backend(Flowise API) does not support context conversation. I will temporarily set it aside.
