### ISSUE TITLE
missing error messages in Bing Image Creator

### ISSUE THREAD

**Issue by jaodei** [hibobmaster/matrix_chatgpt_bot#21]
Hi,

Today when I tested on the bing image creator bot, I saw some of my prompts were blocked by bing after checking with the log info ("Your prompt has been blocked by Bing. Try to change any bad words and try again.") However, there is no such message in Matrix/element UI. I am wondering if it's possible to pass the errors back to the users so that they can know what happened when there was no output at all after timeout?

Also it seems that an error of "Redirect failed" might be due to expired _U cookie, which is not shown either in the user interface.

Not sure if other errors might occur, such as "Could not get results", "Bad images", "No images" etc. defined in file BingImageGen.py.

Cheers.

**Comment by hibobmaster** [comment]
Done!
![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/24900caa-08ac-4964-b5dd-6810d503ad0b)

**Comment by hibobmaster** [comment]
Try the latest version.
https://github.com/hibobmaster/matrix_chatgpt_bot/blob/main/CHANGELOG.md
