### ISSUE TITLE
unable to change keyword for sending command to bard in v1.2.0

### ISSUE THREAD

**Issue by jaodei** [hibobmaster/matrix_chatgpt_bot#24]
I tried to change the keyword from default !bard to say bard, or even empty/null in file bot.py. However it is not working. I still need to use !bard to wake up bard.

This is what I used, which removes the keyword completely.
self.bard_prog = re.compile(r"^(.+)$")

This is what I used, which changes the keyword to bard.
self.bard_prog = re.compile(r"^\s*bard\s*(.+)$")

I've not tested other new features, like session isolation yet.

Cheers.

**Comment by hibobmaster** [comment]
How did you run the bot?

**Comment by jaodei** [comment]
I run via docker compose up -d.
My compose.yaml file is like below. I've changed bot.py as above.

services:
  app:
    image: hibobmaster/matrixchatgptbot:v1.2.0
    container_name: bardbot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./db:/app/db
      - ./bot.py:/app/bot.py
    networks:
      - matrix

**Comment by hibobmaster** [comment]
- ./bot.py:/app/src/bot.py

**Comment by jaodei** [comment]
It works. Thanks.
