### ISSUE TITLE
still no session isolation in bard in v1.2.0

### ISSUE THREAD

**Issue by jaodei** [hibobmaster/matrix_chatgpt_bot#25]
I just tested and found there is still no session isolation in bard in v1.2.0, i.e., cross talk in different rooms is still there. :-(

I've used below in config.json, copied from the sample file. Does it matter? What does flowise api do? Cheers.

  "flowise_api_url": "http://localhost:3000/api/v1/prediction/6deb3c89-45bf-4ac4-a0b0-b2d5ef249d21",
  "flowise_api_key": "U3pe0bbVDWOyoJtsDzFJjRvHKTP3FRjODwuM78exC3A=",

**Comment by hibobmaster** [comment]
You miss understanding session isolation.
Session isolation is user_id based, not room based.

https://github.com/FlowiseAI/Flowise

**Comment by jaodei** [comment]
so you meant I need to define different "USER_ID" in .env file?

If so, I still need to run a few instances, right?

Sorry, I have no understanding of flowise, due to my limited software programming knowledge. can you elaborate more on how to incorporate flowise here? Cheers.

**Comment by hibobmaster** [comment]
User based session isolation means: No matter which rooms you are in, bot will respond to you without inference with other user's prompt.
Nothing should be done in config file and no need to run several instances.

Flowise is a web ui for langchain, it can provide an API after you set it up.

**Comment by jaodei** [comment]
Thanks for the explanation.

So the user here means normal matrix user?

**Comment by hibobmaster** [comment]
Yes.

**Comment by jaodei** [comment]
It works in Bard. Great. Thanks for that.
