### ISSUE TITLE
producing "Service Unavailable" in bing chat

### ISSUE THREAD

**Issue by jaodei** [hibobmaster/matrix_chatgpt_bot#26]
The bing chat bot (created using v1.2.0) produces  "Service Unavailable" possibly due to not having been using for a while (over 10 hours maybe). The error can be quickly resolved by restarting the container. 

Such an issue is not seen in other bots like bard, bing image creator.

Is this due to a mechanism set by microsoft?

**Comment by hibobmaster** [comment]
Sorry I am too busy these days.
> Is this due to a mechanism set by microsoft?

Yes, each conversation will end up in a few hours if no request has been made.
Use `!new bing` to start a new conversation, no need to restart the container.

**Comment by jaodei** [comment]
cool. thanks.

**Comment by hibobmaster** [comment]
I will add a timestamp check in the following updates.
