### ISSUE TITLE
room level and thread level context or both

### ISSUE THREAD

**Issue by seshubonam** [hibobmaster/matrix_chatgpt_bot#29]
https://github.com/matrixgpt/matrix-chatgpt-bot#good-to-know

This popular bot allows the following :

- The bot uses threads by default, to keep the context you should reply to this thread or the bot will think its a new conversation.    "Threads" were previously experimental, you may need to activate them in your client's settings (e.g. in Element in the "lab"-section).
- There is support to set the context to work at either the:
   room level
   thread level
   both (threads fork the conversation from the main room)

any possibility to add this feature? would be very useful for practical use cases in a group chat setting. This also solves the problem of context per user query that we discussed few weeks ago. 

Thanks

**Comment by hibobmaster** [comment]
I have been very busy recently and won't have time until next week. I will look into these features at that time.

**Comment by seshubonam** [comment]
yup sure thanks

**Comment by jaodei** [comment]
Hi, 

> seshubonam

May I know what are the benefits of adding this feature? Cheers.

**Comment by Dual-0** [comment]
> May I know what are the benefits of adding this feature? Cheers.

Thread level is based on the functionality of ChatGPT. The bot keeps the context of the chat inside a thread. If you want the bot to refer to a message, reply to it in the thread. If you don't want it to, you can open a new thread. If you don't have this function, the bot will refer to all previously sent messages and treat them as context.

**Comment by hibobmaster** [comment]
Thread level has `"rel_type": "m.thread"`, it's possible to implement it but It is difficult to maintain and differentiate the relationship between contexts. So for now, let's keep things as they are, with each person's conversation undisturbed, maintaining their own contextual relationships.
![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/d6d5a826-c856-4701-8b6e-82670d97270c)

It seems `unsigned[transaction_id]`  in thread is equal .
```
          "unsigned": {
            "age": 2944662618,
            "transaction_id": "m1692237232973.89"
          },
```

**Comment by seshubonam** [comment]
yup thats good enough ... very good work on repo so far 👏👏

**Comment by mwnu** [comment]
> yup thats good enough ... very good work on repo so far 👏👏是的，这足够好...到目前为止，回购工作非常好👏👏

I believe that having robots reply within threads (message columns) is a better approach. Firstly, use a command (such as !gpt) followed by a prompt to trigger the robot's response. Then, the robot replies within the thread, where users can converse without needing further commands. The robot will gather context from within the thread. This setup allows for multiple topics to be discussed within a single room, avoiding the clutter of long contexts and mixed topics in the message list.Like [this project](https://github.com/matrixgpt/matrix-chatgpt-bot)

**Comment by seshubonam** [comment]
hi, great thought. we are trying threads on a matrix client using this matrix bot. you can checkout the site at https://pixx.co/ the repo at https://github.com/pixxels-team/Pixxels-App 

![Screenshot_20240423_040345_Chrome.jpg](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/1757478/eec48de4-bc74-4151-9174-dad172bb91bc)



![Screenshot_20240423_040358_Chrome.jpg](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/1757478/fa85c1c1-7e00-4662-8d92-54e05249b624)

**Comment by hibobmaster** [comment]
I will look at it. It may take some time to achieve that.

**Comment by hibobmaster** [comment]
To make less changes, i implement thread level context in following steps:
1. mention bot with prompt
2. bot replies in thread
3. send prompt in thread directly without mention it

From web:
![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/d5ba1d69-8bdc-4b77-ada9-15ef7894b0ba)
![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/d7c06c66-5c9b-4a7c-9faf-9aa20b7361ac)
From mobile:
![1713868674293](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/6a8b00ec-bb54-4104-ad5b-e00a85cd2a9d)
![1713868674289](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/e597874b-9de2-499e-bbe2-d70bdd0d084b)

In this way you guy don't need do anything, then we have room level or thread level chat.

**Comment by seshubonam** [comment]
hi, great thought. we are trying threads on a matrix client using this matrix bot. you can checkout the site at https://pixx.co/ the repo at https://github.com/pixxels-team/Pixxels-App 

![Screenshot_20240423_040358_Chrome.jpg](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/1757478/fa85c1c1-7e00-4662-8d92-54e05249b624)

    wow so quick. 
we tried to manage thread context using llm and msgid. but will try this out. thanks again and again and again.

**Comment by hibobmaster** [comment]
In version v1.7.0, room level context is user independent same as before, thread level context is thread independent.

So users can use the same context for a single thread, which make more senses. 🎉
https://github.com/hibobmaster/matrix_chatgpt_bot#thread-level-context

Remember create a blank `context.db` and edit your `compose.yaml` [accordingly](https://github.com/hibobmaster/matrix_chatgpt_bot/blob/69ce5b43a380ccc57a3cf3995a33420bddeeb6ec/compose.yaml#L17) before spinning up new version.

**Comment by seshubonam** [comment]
sure thank you, will check

**Comment by mwnu** [comment]
> In version v1.7.0, room level context is user independent same as before, thread level context is thread independent.
> 
> So users can use the same context for a single thread, which make more senses. 🎉 https://github.com/hibobmaster/matrix_chatgpt_bot#thread-level-context
> 
> Remember create a blank `context.db` and edit your `compose.yaml` [accordingly](https://github.com/hibobmaster/matrix_chatgpt_bot/blob/69ce5b43a380ccc57a3cf3995a33420bddeeb6ec/compose.yaml#L17) before spinning up new version.

The upgrade is fantastic, but there's a minor issue. In the Matrix Spec v1.4, the implementation method for threads involves assigning the value `m.thread` to `rel_type` when an event occurs. However, some clients might use their own tags. For instance, Element Web and Element Desktop might label thread events as `"rel_type": "io.element.thread"`. This is because the server has not yet implemented this version of the Thread MSC, or the client version is outdated, leading to these compatibility changes.
I suggest including "io.element.thread" in the robot's thread response events as well.

**Comment by hibobmaster** [comment]
> > In version v1.7.0, room level context is user independent same as before, thread level context is thread independent.
> > So users can use the same context for a single thread, which make more senses. 🎉 https://github.com/hibobmaster/matrix_chatgpt_bot#thread-level-context
> > Remember create a blank `context.db` and edit your `compose.yaml` [accordingly](https://github.com/hibobmaster/matrix_chatgpt_bot/blob/69ce5b43a380ccc57a3cf3995a33420bddeeb6ec/compose.yaml#L17) before spinning up new version.
> 
> The upgrade is fantastic, but there's a minor issue. In the Matrix Spec v1.4, the implementation method for threads involves assigning the value `m.thread` to `rel_type` when an event occurs. However, some clients might use their own tags. For instance, Element Web and Element Desktop might label thread events as `"rel_type": "io.element.thread"`. This is because the server has not yet implemented this version of the Thread MSC, or the client version is outdated, leading to these compatibility changes. I suggest including "io.element.thread" in the robot's thread response events as well.

Adding `"rel_type": "io.element.thread"` to the response does not work.
![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/e3dcf0cc-e89c-4120-b073-ec5d574ee08a)
![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/a32e2f65-28d4-4421-b7bd-e9c3be8667bf)

**Comment by mwnu** [comment]
> > > In version v1.7.0, room level context is user independent same as before, thread level context is thread independent.
> > > So users can use the same context for a single thread, which make more senses. 🎉 https://github.com/hibobmaster/matrix_chatgpt_bot#thread-level-context
> > > Remember create a blank `context.db` and edit your `compose.yaml` [accordingly](https://github.com/hibobmaster/matrix_chatgpt_bot/blob/69ce5b43a380ccc57a3cf3995a33420bddeeb6ec/compose.yaml#L17) before spinning up new version.
> > 
> > 
> > The upgrade is fantastic, but there's a minor issue. In the Matrix Spec v1.4, the implementation method for threads involves assigning the value `m.thread` to `rel_type` when an event occurs. However, some clients might use their own tags. For instance, Element Web and Element Desktop might label thread events as `"rel_type": "io.element.thread"`. This is because the server has not yet implemented this version of the Thread MSC, or the client version is outdated, leading to these compatibility changes. I suggest including "io.element.thread" in the robot's thread response events as well.
> 
> Adding `"rel_type": "io.element.thread"` to the response does not work. ![image](https://private-user-images.githubusercontent.com/32976627/325179493-e3dcf0cc-e89c-4120-b073-ec5d574ee08a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTQ5NDgsIm5iZiI6MTcxMzk1NDY0OCwicGF0aCI6Ii8zMjk3NjYyNy8zMjUxNzk0OTMtZTNkY2YwY2MtZTg5Yy00MTIwLWIwNzMtZWM1ZDU3NGVlMDhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEwMzA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjZGI4ZTFmNDMwMjc1MDc0Y2Y1ZTkwOTVmYjAwMmNlYTY0YzBkM2RmZTVlODU3OTQ4MDg2YTJhMmJmYmEyZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fSA38PPj-Fw3a9TEN2h4GJRjkRfyaTtqwd7NDQyUuuU) ![image](https://private-user-images.githubusercontent.com/32976627/325179580-a32e2f65-28d4-4421-b7bd-e9c3be8667bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTQ5NDgsIm5iZiI6MTcxMzk1NDY0OCwicGF0aCI6Ii8zMjk3NjYyNy8zMjUxNzk1ODAtYTMyZTJmNjUtMjhkNC00NDIxLWI3YmQtZTljM2JlODY2N2JmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEwMzA0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZGNlOThmNzg5OGNhNzUxYWM1MzJiM2VmZjU4Y2IwMmY3ZDk3ZGVmZTE2YzMyNDE4OGNlNTM1MjhjMWE2NjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mDq2yn7QsWT5ctRU0FGUPSzVdnhesfQWHnDKc0F4FZU)

`"rel_type": "io.element.thread" `replaces `"rel_type": "m.thread"`, rather than treating them as an array.

**Comment by hibobmaster** [comment]
> io.element.thread

If we use `"rel_type": "io.element.thread"`, thread is nether properly display from element web nor element android.
![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/560b4fb9-eedd-4191-88db-e87991a2c3f0)
![Screenshot_2024-04-24-18-40-06-973_im vector app-edit](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/0a550413-ae1e-41df-a073-90fe1e46e871)
![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/2587d00d-3060-4cf3-bce0-aad14f1b98e8)
