### ISSUE TITLE
Supporting chatgpt 4.0?

### ISSUE THREAD

**Issue by jaodei** [hibobmaster/matrix_chatgpt_bot#30]
Does it support chatgpt 4.0 where user can upload a photo/file/etc. and/or get a reply which consists a photo/file/etc.?

I see there is RoomMessageFile event defined in room_events.py in nio package, but I don't know how to get the file from the user and send to openai.

**Comment by hibobmaster** [comment]
Here is a example about how to handle file: https://github.com/hibobmaster/matrix-stt-bot/blob/main/bot.py#L178

**Comment by hibobmaster** [comment]
According to openai api reference: https://platform.openai.com/docs/api-reference/chat/create
I guess It has not supported yet.
