### ISSUE TITLE
pandora is not working

### ISSUE THREAD

**Issue by jaodei** [hibobmaster/matrix_chatgpt_bot#37]
Just noticed pandora is not working (showing 'conversation_id' in the replies). Its official web link at https://github.com/pengzhile/pandora  does not exist anymore. Is something weird happening?

**Comment by hibobmaster** [comment]
The author of pandora create a repo called cocopilot which against the terms of github and his account got banned.
Here is the new repo: https://github.com/zhile-io/pandora

**Comment by hibobmaster** [comment]
And in v1.3.x, i remove support for pandora, because it may lead some confuse for other users.

**Comment by jaodei** [comment]
good to know. Thank you.

So in v 1.3 onwards, there won't be chatgpt access for free based on web?

**Comment by hibobmaster** [comment]
Yes, you can use version v1.2.x for an extended period if it meets your requirements. If you genuinely need the chatgpt web functionality provided by Pandora, I can consider adding it back.

**Comment by jaodei** [comment]
I am OK with v1.2 for the near future. Thank you.

**Comment by hibobmaster** [comment]
Thanks for your understand, any unofficial sollution is unstable, if the author abandon it, it will not work in the future.
