### ISSUE TITLE
Please provide support for the DALL-E 3 model

### ISSUE THREAD

**Issue by mwnu** [hibobmaster/matrix_chatgpt_bot#46]
In cofig.jion:
```
"image_generation_endpoint": "https://xxxxxxx/v1/images/generations",
"image_generation_backend": "openai",
"image_generation_size": "1024x1024",
"image_format": "webp",
```
Then use "!pic" to draw a picture, image generation failed. Errors were identified form my image_generation_endpoint:
```
Exception: 503 Service Unavailable {"error":{"message":"当前分组 home 下对于模型 dall-e 无可用渠道 (request id: 20240424153239939302215CLQ69cNy)","type":"new_api_error"}}
```
The model names should be dall-e-3 or dall-e-2 (which will be deprecated), not dall-e. Even though I manually added dall-e, I ultimately got redirected to dall-e-2. I hope to specify the model type directly in the configuration.

**Comment by hibobmaster** [comment]
With https://github.com/hibobmaster/matrix_chatgpt_bot/commit/9288f9aef80c3909511634e197003af45befd672, the model used for image generation has been changed to`dall-e-3` according to https://platform.openai.com/docs/api-reference/images/create

Please test it by using image: `hibobmaster/matrixchatgptbot:sha-9288f9aef80c3909511634e197003af45befd672`

**Comment by mwnu** [comment]
> With [9288f9a](https://github.com/hibobmaster/matrix_chatgpt_bot/commit/9288f9aef80c3909511634e197003af45befd672), the model used for image generation has been changed to`dall-e-3` according to https://platform.openai.com/docs/api-reference/images/create
> 
> Please test it by using image: `hibobmaster/matrixchatgptbot:sha-9288f9aef80c3909511634e197003af45befd672`

Thank you for the update. It shows as DALL-E-3. Please push it to "latest" later.

**Comment by hibobmaster** [comment]
https://github.com/hibobmaster/matrix_chatgpt_bot/releases/tag/v1.7.1
