### ISSUE TITLE
Sometimes, there is no response to prompts,

### ISSUE THREAD

**Issue by mwnu** [hibobmaster/matrix_chatgpt_bot#47]
And errors only appear in the logs after a reboot:
![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/45463732/290f06e4-c2a0-429a-b8d4-0d5350810796)

1. **File and Line Numbers**:
   - `File "/app/src/main.py", line 125`: The error occurs at line 125 in `main.py`, where `asyncio.run(main())` is called to execute the `main` function.
   - `File "/app/src/main.py", line 120`: At line 120 in the `main` function, there is an `await sync_task` statement waiting for an asynchronous task to complete.

2. **Error Type**:
   - `asyncio.exceptions.CancelledError`: This is an exception specific to `asyncio`, indicating that an asynchronous task was cancelled.

3. **Context of the Error**:
   - The error occurs within the `sync_forever` function, where the program awaits a response (`await self.run_response_callbacks([await response])`). This function is called in a loop to continuously sync data.
   - The error happens in the `get` method of `asyncio/queues.py`, indicating that the task was cancelled while attempting to retrieve it from a queue.

4. **Timestamps in the Log**:
   - The error happens at `2024-04-24 16:04:56`.
   - Shortly after, at `2024-04-24 16:05:02`, the log indicates "matrix chatgpt bot start.....", suggesting that despite the error, the program might be trying to restart or continue execution.

5. **Possible Causes**:
   - `CancelledError` typically results from parts of the program explicitly cancelling a task, or from tasks not being properly completed during shutdown/restart processes.
   - In this case, the cancellation might be triggered by the `Bot closed!` event (indicated by `INFO - Bot closed!` in the log), initiating some cleanup process that cancels the ongoing asynchronous tasks.

6. **Handling**:
   - Review how asynchronous tasks are managed in the program to ensure they are properly completed or orderly cancelled when the program attempts to shut down.
   - Consider adding appropriate error handling logic in the code to manage `CancelledError`, such as using `try...except` blocks to catch this exception and perform necessary cleanup.

**Comment by hibobmaster** [comment]
This error can be safely ignored.

If you stuck at bot starting, try restart it.
![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/26ae86c6-8314-414e-b567-a6228222f254)

**Comment by mwnu** [comment]
> This error can be safely ignored.
> 
> If you stuck at bot starting, try restart it. ![image](https://private-user-images.githubusercontent.com/32976627/325145493-26ae86c6-8314-414e-b567-a6228222f254.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDk0NDUsIm5iZiI6MTcxMzk0OTE0NSwicGF0aCI6Ii8zMjk3NjYyNy8zMjUxNDU0OTMtMjZhZTg2YzYtODMxNC00MTRlLWI1NjctYTYyMjgyMjJmMjU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA4NTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwN2UwYzFkMzQ0MGIyMzkzMmEwZmYxNTJkOGU3OGZmYzU4NzczOTBjZGM3MGIxMWFkOGMxMmUzMWY3NTk3NmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L9VLQkww7UcL1VyHHDNkX6Zuuxmp3cVPYnmQFPLqmvI)

I've figured out where the problem lies. The format of the submission events sent from different clients is not the same. I'm not sure why, but this is a message sent from Element Android tagged with @bot, which appears as a rich text link (even though I've turned off rich text input on the mobile app). The bot does not respond to this message:

```
"content": {
    "body": "GPT:  hello - element android",
    "format": "org.matrix.custom.html",
    "formatted_body": "<a href=\"https://matrix.to/#/@gptbot2:xxx.xyz\">GPT</a>:  hello - element android",
    "msgtype": "m.text"
  },
```
The messages I send from Element PC to @bot are normal submission events, and the bot will respond accordingly:

```
"content": {
    "body": "GPT: hello - element desktop",
    "format": "org.matrix.custom.html",
    "formatted_body": "<a href=\"https://matrix.to/#/@gptbot2:xxx.xyz\">GPT</a>: hello - element desktop",
    "m.mentions": {
      "user_ids": [
        "@gptbot2:xxx.xyz"
      ]
    },
    "msgtype": "m.text"
  },
```
I suggest adding a customizable command (such as -gpt prompt) in addition to the @ mention to trigger replies within a thread.

**Comment by hibobmaster** [comment]
Thank you for providing this debug information, i will find a solution.

Edit: i can reproduce it on my device.

**Comment by hibobmaster** [comment]
https://github.com/hibobmaster/matrix_chatgpt_bot/commit/b9a5884fd11246a8756a7d72baaa72efea0778b0

![1713954711777](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/0a5674ca-f4e2-4d47-8251-34f0cdfbdbed)
![1713954711772](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/a336b6df-8d59-475a-8bf2-a43019240df9)

**Comment by hibobmaster** [comment]
Try image: `hibobmaster/matrixchatgptbot:sha-b9a5884fd11246a8756a7d72baaa72efea0778b0`

**Comment by mwnu** [comment]
> sha-b9a5884fd11246a8756a7d72baaa72efea0778b0



> Try image: `hibobmaster/matrixchatgptbot:sha-b9a5884fd11246a8756a7d72baaa72efea0778b0` 尝试镜像: `hibobmaster/matrixchatgptbot:sha-b9a5884fd11246a8756a7d72baaa72efea0778b0`

Success! Thank you.👏

**Comment by hibobmaster** [comment]
https://github.com/hibobmaster/matrix_chatgpt_bot/releases/tag/v1.7.1
