### ISSUE TITLE
Robots do not respond to messages with "!v"

### ISSUE THREAD

**Issue by mwnu** [hibobmaster/matrix_chatgpt_bot#48]
"gpt_vision_api_endpoint": "https://xxxx/v1/chat/completions",
"gpt_vision_model": "gpt-4-turbo",
```
"content": {
    "body": "!v Please explain the above diagram.",
    "format": "org.matrix.custom.html",
    "formatted_body": "!v Please explain the above diagram.",
    "msgtype": "m.text"
  }
```
No response, no logs.

**Comment by hibobmaster** [comment]
You should quote a image. Besides, gpt vision won't work in E2EE room.
![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/aef4c2d9-6a34-49d6-8249-eb6e6b7cd8eb)
![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/bac2d334-07c3-4e93-ba7e-86b2a45a7aab)

**Comment by mwnu** [comment]
> You should quote a image. Besides, gpt vision won't work in E2EE room. ![image](https://private-user-images.githubusercontent.com/32976627/325225585-aef4c2d9-6a34-49d6-8249-eb6e6b7cd8eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjU3NjAsIm5iZiI6MTcxMzk2NTQ2MCwicGF0aCI6Ii8zMjk3NjYyNy8zMjUyMjU1ODUtYWVmNGMyZDktNmEzNC00OWQ2LTgyNDktZWI2ZTZiN2NkOGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEzMzEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MTAzZDA0YmViMDg4NTVkYWQzZTg2MWU4ZGM5MzMwMjE1NjdiYjg2ZDJmNzRhOTc0OWFkNGI5MGNiYmMyOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d1M-OT44McIn4-PdmMKmr_vWdguyCnj6-cdPZf2DB48) ![image](https://private-user-images.githubusercontent.com/32976627/325225636-bac2d334-07c3-4e93-ba7e-86b2a45a7aab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjU3NjAsIm5iZiI6MTcxMzk2NTQ2MCwicGF0aCI6Ii8zMjk3NjYyNy8zMjUyMjU2MzYtYmFjMmQzMzQtMDdjMy00ZTkzLWJhN2UtODZiMmE0NWE3YWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEzMzEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4N2E3OWRjZTk4ZWZhNzc3M2E2OTg2MDAwOTQ0Mjc1MzFmMmZhZTZiMWM1M2FhMTgzNGEyYzdhOWNiMDY2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xvZmBwyr4tTvbnkpGxb2u2G3TtmNnN4rcljQBpFmVgY)

I use @+!v, and it responds twice; the first time, it indicates that it doesn't know.

**Comment by hibobmaster** [comment]
Like thread level chatting for element android before, `!v` gpt vision command won't work...
No `m.mentions` from element android cause a lot of inconvinient things.
https://github.com/hibobmaster/matrix_chatgpt_bot/blob/90a00c9b5aa95cdc2e29f1b6eefe31ebcf3c1e69/src/bot.py#L378-L386

**Comment by hibobmaster** [comment]
Can you provide a screenshot?

**Comment by mwnu** [comment]
> Can you provide a screenshot?

![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/45463732/813e4f89-747c-4c9e-8bb0-254f433783de)

**Comment by hibobmaster** [comment]
I know what's wrong. When we mention the bot, it trigger thread chat as the same time.
![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/3fc6fff5-8021-4c41-8ee3-685f2e2829f9)

**Comment by mwnu** [comment]
> I know what's wrong. When we mention the bot, it trigger thread chat as the same time. ![image](https://private-user-images.githubusercontent.com/32976627/325248463-3fc6fff5-8021-4c41-8ee3-685f2e2829f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5Njc4MDgsIm5iZiI6MTcxMzk2NzUwOCwicGF0aCI6Ii8zMjk3NjYyNy8zMjUyNDg0NjMtM2ZjNmZmZjUtODAyMS00YzQxLThlZTMtNjg1ZjJlMjgyOWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDE0MDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMDNhN2Q5NzJmY2YyNjQyNjVhOTdiZjFiZDM1ODIzNzJkNTM1NTZmMjU3Y2MwZmZhZGZlZDBkZTk3NGZkMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q2242gfeSZmWJgmIuw2tfbIpDvtxVxjopuGc3kFDPlc)

Perhaps the command "!v" can be omitted. Instead, different models could be invoked based on the event's mimetype, as some models, such as gpt-4-turbo and claude-3, support vision.

**Comment by hibobmaster** [comment]
With https://github.com/hibobmaster/matrix_chatgpt_bot/commit/81543d561b46df4158892324172b5145e44f0e32, mention bot 
- with image will trigger gpt vision
- with plain text will trigger thread level chatting


Try image: `hibobmaster/matrixchatgptbot:sha-81543d561b46df4158892324172b5145e44f0e32`
![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/4ad7aefe-0323-4974-afed-66dec6cb98e4)
![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/f969d24e-254e-44e1-a226-532114bcb7ec)

**Comment by mwnu** [comment]
> sha-81543d561b46df4158892324172b5145e44f0e32

Robot can now recognize images in rooms without !v, but they cannot perform this function within threads. Additionally, commands like !pic, !help, and !lc are also unusable in threads, indicating that the two interaction modes are not well integrated. Of course, commands such as !gpt, !chat, and !new are unnecessary in threads. However, due to the poor compatibility of "io.element.thread" (Element PC's implementation for servers that do not support the Matrix standard threads) on client devices (it does not display on mobile phones), retaining these commands is still essential.

**Comment by mwnu** [comment]
> With [81543d5](https://github.com/hibobmaster/matrix_chatgpt_bot/commit/81543d561b46df4158892324172b5145e44f0e32), mention bot
> 
> * with image will trigger gpt vision
> * with plain text will trigger thread level chatting
> 
> Try image: `hibobmaster/matrixchatgptbot:sha-81543d561b46df4158892324172b5145e44f0e32` ![image](https://private-user-images.githubusercontent.com/32976627/325274928-4ad7aefe-0323-4974-afed-66dec6cb98e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjQ4MzUsIm5iZiI6MTcxNDAyNDUzNSwicGF0aCI6Ii8zMjk3NjYyNy8zMjUyNzQ5MjgtNGFkN2FlZmUtMDMyMy00OTc0LWFmZWQtNjZkZWM2Y2I5OGU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA1NTUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiNjQ4MmRlMmE1NTdjODJiYWY2MjAzMDUxYzVkYzkxNDhiNGY5NDQwZGMzNzA5MTUzZTZiYTE1N2Q3Y2U2NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n8WBjDx_inUqdn-JWHV0chiVGiNJi2k0lmmF7d4ANY8) ![image](https://private-user-images.githubusercontent.com/32976627/325280356-f969d24e-254e-44e1-a226-532114bcb7ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMjQ4MzUsIm5iZiI6MTcxNDAyNDUzNSwicGF0aCI6Ii8zMjk3NjYyNy8zMjUyODAzNTYtZjk2OWQyNGUtMjU0ZS00NGUxLWEyMjYtNTMyMTE0YmNiN2VjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA1NTUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZTE4YzE4MDcwZGE0ZWVhZTI0ZTI5ZTc1YjlmMTU5NDg5YjkxMmRjZDAwMjAzZTAzN2IxNTdlYTU2ZmY3MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jjTuVf9AAeIk20oDfdp0F-KOaVtuNQWPJyVewDF7uUU)

Some of the robot's responses are displayed entirely in red font, while others are not. It appears that the `<mx-reply>` `<blockquote>` tags have been added in the HTML. Is this another way of implementing the reply function in Matrix? Very strange!

**Comment by hibobmaster** [comment]
https://github.com/hibobmaster/matrix_chatgpt_bot/commit/c5834db9b270181a9987aff05c311d6c698a3d49
Try image: `hibobmaster/matrixchatgptbot:sha-c5834db9b270181a9987aff05c311d6c698a3d49`
![Screenshot_2024-04-26-01-31-19-448_im vector app-edit](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/6399b3da-c3ba-4aa9-b08c-626686111537)

**Comment by mwnu** [comment]
> sha-c5834db9b270181a9987aff05c311d6c698a3d49

I tested it, and these commands execute successfully within threads. They seem to be independent of the thread context. For example, after uploading a picture, the bot cannot describe it directly. Instead, it requires a separate reply to reference it, and the bot's response is not considered part of the thread context. Of course, the current method is okay, almost like a thread within a thread 😀. This can reduce unnecessary context, which can be referenced separately when needed.

**Comment by hibobmaster** [comment]
> the bot cannot describe it directly

GPT Vision has a prompt which should be provided by user since matrix doesn't support sending a image with description.

> and the bot's response is not considered part of the thread context

Try image: `hibobmaster/matrixchatgptbot:v1.7.2`

![image](https://github.com/hibobmaster/matrix_chatgpt_bot/assets/32976627/54e358d4-57e8-45db-8b39-19978fb59465)

**Comment by mwnu** [comment]
> > the bot cannot describe it directly
> 
> GPT Vision has a prompt which should be provided by user since matrix doesn't support sending a image with description.
> 
> > and the bot's response is not considered part of the thread context
> 
> Try image: `hibobmaster/matrixchatgptbot:v1.7.2`
> 
> ![image](https://private-user-images.githubusercontent.com/32976627/325916974-54e358d4-57e8-45db-8b39-19978fb59465.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMzYxMDgsIm5iZiI6MTcxNDEzNTgwOCwicGF0aCI6Ii8zMjk3NjYyNy8zMjU5MTY5NzQtNTRlMzU4ZDQtNTdlOC00NWRiLThiMzktMTk5NzhmYjU5NDY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDEyNTAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkZjY4NjkzMGU0MGRkMzRjODk5OTJmYjRmZGY2MjE0M2RmYjc0NzBiMjZkMWRlODNkNjQxYTAxYWNkZTUwMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-5NynM4-pMzrxJ3CsMf0XHsUWiCkUYzD5JPT5jkJfk0)

done👍
