### ISSUE TITLE
v1.8.0 no longer supports all rooms. If "room_id" is not set in the configuration, a runtime error will occur.

### ISSUE THREAD

**Issue by mwnu** [hibobmaster/matrix_chatgpt_bot#53]
I recommend retaining the previous version's approach: if left empty, support all rooms.
if a domain is set (e.g., :example.com), then only support rooms for the specified domain.

**Comment by hibobmaster** [comment]
Try the image: `hibobmaster/matrixchatgptbot:sha-f568c0bc1a1bf2fdf244a16259a943a3db6b59bf`

**Comment by mwnu** [comment]
> Try the image: `hibobmaster/matrixchatgptbot:sha-f568c0bc1a1bf2fdf244a16259a943a3db6b59bf`

The new image fixes the issue where "room_id" was not configured

**Comment by hibobmaster** [comment]
https://github.com/hibobmaster/matrix_chatgpt_bot/releases/tag/v1.8.1
