### ISSUE TITLE
Support for ollama

### ISSUE THREAD

**Issue by pmffromspace** [hibobmaster/matrix_chatgpt_bot#57]
Hey there is the support for ollama planned?
I tried, and tought ollama api and openAI api are same but i cant get it working.

Kind regards
pmf

**Comment by hibobmaster** [comment]
Hi, ollama works on well by using the [OpenAI API](https://github.com/ollama/ollama/blob/main/docs/openai.md).
Here is a working config:
```json
{
    "homeserver": "https://<redacted>",
    "user_id": "@<redacted>:<redacted>",
    "password": "<redacted>",
    "device_id": "matrix_chatgpt_bot",
    "gpt_api_endpoint": "http://192.168.0.163:11434/v1/chat/completions",
    "gpt_model": "qwen2.5"
}
```
Make sure `http://192.168.0.163:11434/v1/chat/completions` is accessable by matrix_chatgpt_bot.

**Comment by pmffromspace** [comment]
Thanks a lot that solved the issue!
